# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_signal_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(604, 317)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.I = QtWidgets.QPushButton(Form)
        self.I.setObjectName("I")
        self.gridLayout.addWidget(self.I, 0, 0, 1, 1)
        self.II = QtWidgets.QPushButton(Form)
        self.II.setObjectName("II")
        self.gridLayout.addWidget(self.II, 0, 1, 1, 1)
        self.III = QtWidgets.QPushButton(Form)
        self.III.setObjectName("III")
        self.gridLayout.addWidget(self.III, 1, 0, 1, 1)
        self.AVR = QtWidgets.QPushButton(Form)
        self.AVR.setObjectName("AVR")
        self.gridLayout.addWidget(self.AVR, 1, 1, 1, 1)
        self.AVL = QtWidgets.QPushButton(Form)
        self.AVL.setObjectName("AVL")
        self.gridLayout.addWidget(self.AVL, 2, 0, 1, 1)
        self.AVF = QtWidgets.QPushButton(Form)
        self.AVF.setObjectName("AVF")
        self.gridLayout.addWidget(self.AVF, 2, 1, 1, 1)
        self.V1 = QtWidgets.QPushButton(Form)
        self.V1.setObjectName("V1")
        self.gridLayout.addWidget(self.V1, 3, 0, 1, 1)
        self.V2 = QtWidgets.QPushButton(Form)
        self.V2.setObjectName("V2")
        self.gridLayout.addWidget(self.V2, 3, 1, 1, 1)
        self.V3 = QtWidgets.QPushButton(Form)
        self.V3.setObjectName("V3")
        self.gridLayout.addWidget(self.V3, 4, 0, 1, 1)
        self.V4 = QtWidgets.QPushButton(Form)
        self.V4.setObjectName("V4")
        self.gridLayout.addWidget(self.V4, 4, 1, 1, 1)
        self.V5 = QtWidgets.QPushButton(Form)
        self.V5.setObjectName("V5")
        self.gridLayout.addWidget(self.V5, 5, 0, 1, 1)
        self.V6 = QtWidgets.QPushButton(Form)
        self.V6.setObjectName("V6")
        self.gridLayout.addWidget(self.V6, 5, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.all = QtWidgets.QPushButton(Form)
        self.all.setObjectName("all")
        self.verticalLayout.addWidget(self.all)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.I.setText(_translate("Form", "I"))
        self.II.setText(_translate("Form", "II"))
        self.III.setText(_translate("Form", "III"))
        self.AVR.setText(_translate("Form", "AVR"))
        self.AVL.setText(_translate("Form", "AVL"))
        self.AVF.setText(_translate("Form", "AVF"))
        self.V1.setText(_translate("Form", "V1"))
        self.V2.setText(_translate("Form", "V2"))
        self.V3.setText(_translate("Form", "V3"))
        self.V4.setText(_translate("Form", "V4"))
        self.V5.setText(_translate("Form", "V5"))
        self.V6.setText(_translate("Form", "V6"))
        self.all.setText(_translate("Form", "全部"))
