# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'states.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(687, 298)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(main)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(main)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(main)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(main)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(main)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.fs = QtWidgets.QLineEdit(main)
        self.fs.setInputMask("")
        self.fs.setText("")
        self.fs.setObjectName("fs")
        self.horizontalLayout_2.addWidget(self.fs)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.quzao = QtWidgets.QPushButton(main)
        self.quzao.setObjectName("quzao")
        self.horizontalLayout_3.addWidget(self.quzao)
        self.WVD = QtWidgets.QPushButton(main)
        self.WVD.setObjectName("WVD")
        self.horizontalLayout_3.addWidget(self.WVD)
        self.STFT = QtWidgets.QPushButton(main)
        self.STFT.setObjectName("STFT")
        self.horizontalLayout_3.addWidget(self.STFT)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.WCT = QtWidgets.QPushButton(main)
        self.WCT.setObjectName("WCT")
        self.horizontalLayout_4.addWidget(self.WCT)
        self.HHTp = QtWidgets.QPushButton(main)
        self.HHTp.setObjectName("HHTp")
        self.horizontalLayout_4.addWidget(self.HHTp)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Form"))
        self.label.setText(_translate("main", "输入信号文件路径"))
        self.lineEdit.setPlaceholderText(_translate("main", "请选择格式为.json的文件："))
        self.label_2.setText(_translate("main", "输出文件路径"))
        self.lineEdit_2.setPlaceholderText(_translate("main", "请选择保存文件的目录："))
        self.fs.setPlaceholderText(_translate("main", "请输入采样频率："))
        self.quzao.setText(_translate("main", "去噪"))
        self.WVD.setText(_translate("main", "WVD"))
        self.STFT.setText(_translate("main", "短时傅里叶变换"))
        self.WCT.setText(_translate("main", "小波变换"))
        self.HHTp.setText(_translate("main", "HHT"))
